language: go
go_import_path: macleod.io/bounce
go:
- 1.7.1
install:
- go get -v github.com/Masterminds/glide
- glide install
script:
- go build
- ./build.sh
- go test -bench=. -run=^a $(glide nv)
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
