language: go
go_import_path: macleod.io/bounce
go:
- 1.7.1
install:
- mkdir "$GOPATH/bin"
- bash <(curl -s https://glide.sh/get)
- glide install
script:
- go build
- ./build.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
