language: go
go_import_path: macleod.io/bounce
go:
- 1.7.1
install:
- go get -v github.com/onsi/ginkgo/ginkgo
- go get -v github.com/Masterminds/glide
- glide install
script:
- go build
- ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress
- find . -iname \*.coverprofile -exec cat {} + > coverage.txt
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
